# Generated by Django 5.2 on 2025-04-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programasposgrado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestrias',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
