# Generated by Django 5.2 on 2025-04-24 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programasposgrado', '0003_cohortes_maestriacohortemodalidad_modalidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cohortes',
            old_name='nombre',
            new_name='cohorte',
        ),
    ]
