# Generated by Django 5.2 on 2025-04-25 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programasposgrado', '0004_rename_nombre_cohortes_cohorte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cohortes',
            options={'ordering': ['fecha_inicio'], 'verbose_name': 'Cohorte'},
        ),
    ]
