# Generated by Django 5.2 on 2025-05-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programasposgrado', '0005_alter_cohortes_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoAmplio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campo Amplio',
                'ordering': ['-created'],
            },
        ),
    ]
