# Generated by Django 5.2 on 2025-05-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programasposgrado', '0006_campoamplio'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestriacohortemodalidad',
            name='campoamplio',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
