# Generated by Django 5.2 on 2025-05-13 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programasposgrado', '0007_maestriacohortemodalidad_campoamplio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codificacion', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('maestria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='programasposgrado.maestrias')),
            ],
            options={
                'verbose_name': 'Modulo',
                'ordering': ['-created'],
            },
        ),
    ]
