# Generated by Django 5.2 on 2025-05-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programasposgrado', '0008_modulos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodosAcademicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cohorte',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.DeleteModel(
            name='Cohortes',
        ),
    ]
