# Generated by Django 5.2 on 2025-05-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programasposgrado', '0009_periodosacademicos_delete_cohortes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaPosgrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maestria', models.BigIntegerField()),
                ('campoamplio', models.BigIntegerField()),
                ('periodoacademico', models.BigIntegerField()),
                ('modalidad', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Programa de Posgrado',
                'ordering': ['-created'],
            },
        ),
    ]
