# Generated by Django 5.2 on 2025-05-15 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuerpoacademico', '0004_alter_composicionca_programadeposgrado_and_more'),
        ('programaacademico', '0006_alter_admision_programadeposgrado_and_more'),
        ('programasposgrado', '0010_programaposgrado'),
        ('rae', '0003_alter_reactivosmultiplechoice_programadeposgrado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaestriaCohorteModalidad',
        ),
        migrations.AlterModelOptions(
            name='periodosacademicos',
            options={'ordering': ['fecha_inicio'], 'verbose_name': 'PeriodosAcademicos'},
        ),
    ]
