# Generated by Django 5.2 on 2025-05-29 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programasposgrado', '0012_programaposgrado_cohorte'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialidadesMedicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Especialidad Medica',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaPosgradoEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.BigIntegerField()),
                ('campoamplio', models.BigIntegerField()),
                ('periodoacademico', models.BigIntegerField()),
                ('modalidad', models.BigIntegerField()),
                ('cohorte', models.IntegerField(choices=[(1, 'Primera'), (2, 'Segunda'), (3, 'Tercera'), (4, 'Cuarta'), (5, 'Quinta'), (6, 'Sexta'), (7, 'Septima'), (8, 'Octava'), (9, 'Novena'), (10, 'Decima')])),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Programa de Posgrado EM',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ModulosEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codificacion', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos_especialidad', to='programasposgrado.especialidadesmedicas')),
            ],
            options={
                'verbose_name': 'Modulo Especialidad Médica',
                'ordering': ['-created'],
            },
        ),
    ]
