# Generated by Django 5.2 on 2025-10-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programasposgrado', '0013_especialidadesmedicas_programaposgradoem_modulosem'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestrias',
            name='resolucion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maestrias',
            name='titulootorgado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='programaposgrado',
            name='fechafin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programaposgrado',
            name='fechainicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programaposgrado',
            name='horarioclases',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programaposgrado',
            name='ultimoajuste',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
