# Generated by Django 5.2 on 2025-10-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programasposgrado', '0014_maestrias_resolucion_maestrias_titulootorgado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalidadDeTitulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidadtitulacion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Modalidad de Titulación',
                'ordering': ['-created'],
            },
        ),
    ]
