# Generated by Django 5.2 on 2026-03-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programasposgrado', '0015_modalidaddetitulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaposgrado',
            name='num_semanas_programa',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programaposgradoem',
            name='fechafin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programaposgradoem',
            name='fechainicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programaposgradoem',
            name='num_semanas_programa',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
