# Generated by Django 5.2 on 2025-05-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContratosDocentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.IntegerField()),
                ('programadeposgrado', models.IntegerField()),
                ('modulo', models.IntegerField()),
                ('horasacademicas', models.IntegerField()),
                ('valorxhora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('certificacionpresupuestaria', models.CharField(max_length=100)),
                ('fechacertificacionpresupuestaria', models.DateField()),
                ('plazo', models.CharField(max_length=100)),
                ('numerocontrato', models.CharField(max_length=100)),
                ('tipopersonalacademico', models.CharField(max_length=100)),
                ('adenda', models.CharField(blank=True, max_length=100, null=True)),
                ('obsevaciones', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contratos Docentes',
                'ordering': ['-created'],
            },
        ),
    ]
