# Generated by Django 5.2 on 2025-05-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosposgrado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratosdocentes',
            name='tipopersonalacademico',
            field=models.IntegerField(choices=[(1, 'Servicios profesionales')], default=1),
        ),
    ]
