# Generated by Django 5.2 on 2025-05-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosposgrado', '0002_alter_contratosdocentes_tipopersonalacademico'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratosdocentes',
            name='numeromemorandotthh',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
