# Generated by Django 5.2 on 2025-06-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosposgrado', '0003_contratosdocentes_numeromemorandotthh'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor', models.IntegerField()),
                ('programadeposgrado', models.IntegerField()),
                ('maestrante', models.IntegerField()),
                ('plazo', models.CharField(max_length=100)),
                ('certificacionpresupuestaria', models.CharField(max_length=100)),
                ('fechacertificacionpresupuestaria', models.DateField()),
                ('valorcontrato', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numerocontrato', models.CharField(max_length=100)),
                ('numeromemorandotthh', models.CharField(max_length=100)),
                ('tipopersonalacademico', models.IntegerField(choices=[(1, 'Servicios profesionales')], default=1)),
                ('adenda', models.CharField(blank=True, max_length=100, null=True)),
                ('obsevaciones', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contrato Tutor',
                'ordering': ['-created'],
            },
        ),
    ]
