# Generated by Django 5.2 on 2025-06-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosposgrado', '0004_contratotutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoCoordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinador', models.IntegerField()),
                ('programadeposgrado', models.IntegerField()),
                ('certificacionpresupuestaria', models.CharField(max_length=100)),
                ('fechacertificacionpresupuestaria', models.DateField()),
                ('plazo', models.CharField(max_length=100)),
                ('honorario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numerocontrato', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('noactasseleccion', models.CharField(max_length=100)),
                ('oficioentregadoporth', models.CharField(max_length=100)),
                ('modalidadcontractuar', models.CharField(max_length=100)),
                ('obsevaciones', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contrato Coordinador',
                'ordering': ['-created'],
            },
        ),
    ]
