# Generated by Django 5.2 on 2025-06-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosposgrado', '0005_contratocoordinador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratocoordinador',
            name='honorario',
            field=models.CharField(max_length=100),
        ),
    ]
