# Generated by Django 5.2 on 2025-06-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosposgrado', '0006_alter_contratocoordinador_honorario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratocoordinador',
            name='honorario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
