# Generated by Django 5.2 on 2025-06-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datosposgrado', '0007_alter_contratocoordinador_honorario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratocoordinador',
            options={'ordering': ['-created'], 'verbose_name': 'Contratos Docentes'},
        ),
    ]
