# Generated by Django 5.2 on 2025-10-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosposgrado', '0008_alter_contratocoordinador_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratocoordinador',
            name='urldocumento',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contratosdocentes',
            name='urldocumento',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contratotutor',
            name='urldocumento',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
