# Generated by Django 5.2 on 2025-10-23 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datosposgrado', '0009_contratocoordinador_urldocumento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contratocoordinador',
            old_name='obsevaciones',
            new_name='observaciones',
        ),
        migrations.RenameField(
            model_name='contratosdocentes',
            old_name='obsevaciones',
            new_name='observaciones',
        ),
        migrations.RenameField(
            model_name='contratotutor',
            old_name='obsevaciones',
            new_name='observaciones',
        ),
    ]
