# Generated by Django 5.2 on 2025-10-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosposgrado', '0010_rename_obsevaciones_contratocoordinador_observaciones_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratocoordinador',
            options={'ordering': ['-created'], 'verbose_name': 'Contrato de Coordinador', 'verbose_name_plural': 'Contratos de Coordinador'},
        ),
        migrations.AlterModelOptions(
            name='contratosdocentes',
            options={'ordering': ['-created'], 'verbose_name': 'Contrato Docente', 'verbose_name_plural': 'Contratos Docentes'},
        ),
        migrations.AlterModelOptions(
            name='contratotutor',
            options={'ordering': ['-created'], 'verbose_name': 'Contrato de Tutor', 'verbose_name_plural': 'Contratos de Tutor'},
        ),
        migrations.AddField(
            model_name='contratocoordinador',
            name='fechafin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratocoordinador',
            name='fechainicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contratocoordinador',
            name='plazo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
