# Generated by Django 5.2 on 2026-02-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosposgrado', '0011_alter_contratocoordinador_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratocoordinador',
            name='programa_tipo',
            field=models.CharField(choices=[('M', 'Maestría'), ('EM', 'Especialidad Médica')], default='M', max_length=2),
        ),
        migrations.AddField(
            model_name='contratosdocentes',
            name='docente_tipo',
            field=models.IntegerField(choices=[(1, 'Docente'), (2, 'Docente de práctica asistencial')], default=1),
        ),
        migrations.AddField(
            model_name='contratosdocentes',
            name='programa_tipo',
            field=models.CharField(choices=[('M', 'Maestría'), ('EM', 'Especialidad Médica')], default='M', max_length=2),
        ),
        migrations.AddField(
            model_name='contratotutor',
            name='programa_tipo',
            field=models.CharField(choices=[('M', 'Maestría'), ('EM', 'Especialidad Médica')], default='M', max_length=2),
        ),
    ]
