# Generated by Django 5.2 on 2026-02-27 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('datosposgrado', '0012_contratocoordinador_programa_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratocoordinador',
            name='programa_tipo',
        ),
        migrations.RemoveField(
            model_name='contratocoordinador',
            name='programadeposgrado',
        ),
        migrations.RemoveField(
            model_name='contratosdocentes',
            name='modulo',
        ),
        migrations.RemoveField(
            model_name='contratosdocentes',
            name='programa_tipo',
        ),
        migrations.RemoveField(
            model_name='contratosdocentes',
            name='programadeposgrado',
        ),
        migrations.RemoveField(
            model_name='contratotutor',
            name='programa_tipo',
        ),
        migrations.RemoveField(
            model_name='contratotutor',
            name='programadeposgrado',
        ),
        migrations.AddField(
            model_name='contratocoordinador',
            name='programa_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'programasposgrado'), ('model', 'programaposgrado')), models.Q(('app_label', 'programasposgrado'), ('model', 'programaposgradoem')), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ct_contratos_coord_programa', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='contratocoordinador',
            name='programa_object_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='contratosdocentes',
            name='modulo_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'programasposgrado'), ('model', 'modulos')), models.Q(('app_label', 'programasposgrado'), ('model', 'modulosem')), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ct_contratos_docentes_modulo', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='contratosdocentes',
            name='modulo_object_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='contratosdocentes',
            name='programa_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'programasposgrado'), ('model', 'programaposgrado')), models.Q(('app_label', 'programasposgrado'), ('model', 'programaposgradoem')), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ct_contratos_docentes_programa', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='contratosdocentes',
            name='programa_object_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='contratotutor',
            name='programa_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'programasposgrado'), ('model', 'programaposgrado')), models.Q(('app_label', 'programasposgrado'), ('model', 'programaposgradoem')), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ct_contratos_tutor_programa', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='contratotutor',
            name='programa_object_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='contratocoordinador',
            name='coordinador',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='contratosdocentes',
            name='docente',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='contratotutor',
            name='maestrante',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='contratotutor',
            name='tutor',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='contratocoordinador',
            index=models.Index(fields=['programa_content_type', 'programa_object_id'], name='datosposgra_program_1def2c_idx'),
        ),
        migrations.AddIndex(
            model_name='contratocoordinador',
            index=models.Index(fields=['coordinador', 'created'], name='datosposgra_coordin_3d2417_idx'),
        ),
        migrations.AddIndex(
            model_name='contratosdocentes',
            index=models.Index(fields=['programa_content_type', 'programa_object_id'], name='datosposgra_program_eb7975_idx'),
        ),
        migrations.AddIndex(
            model_name='contratosdocentes',
            index=models.Index(fields=['modulo_content_type', 'modulo_object_id'], name='datosposgra_modulo__6a00dd_idx'),
        ),
        migrations.AddIndex(
            model_name='contratosdocentes',
            index=models.Index(fields=['docente', 'created'], name='datosposgra_docente_a28ccf_idx'),
        ),
        migrations.AddIndex(
            model_name='contratotutor',
            index=models.Index(fields=['programa_content_type', 'programa_object_id'], name='datosposgra_program_9f8b6d_idx'),
        ),
        migrations.AddIndex(
            model_name='contratotutor',
            index=models.Index(fields=['tutor', 'created'], name='datosposgra_tutor_ae67e8_idx'),
        ),
        migrations.AddIndex(
            model_name='contratotutor',
            index=models.Index(fields=['maestrante', 'created'], name='datosposgra_maestra_b46d18_idx'),
        ),
    ]
