# Generated by Django 5.2 on 2026-04-13 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosposgrado', '0013_remove_contratocoordinador_programa_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contratocoordinador',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_coordinador_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contratosdocentes',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_docentes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contratotutor',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_tutor_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
