# Generated by Django 5.2 on 2025-05-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfilusuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.IntegerField(blank=True, choices=[(1, 'Estudiante'), (2, 'Docente'), (3, 'Coordinador'), (4, 'Editor')], max_length=1, null=True),
        ),
    ]
