# Generated by Django 5.2 on 2025-05-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_perfilusuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.IntegerField(blank=True, choices=[(1, 'Estudiante'), (2, 'Docente'), (3, 'Coordinador'), (4, 'Editor')], null=True),
        ),
    ]
