# Generated by Django 5.2 on 2025-05-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_perfilusuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='ci',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
