# Generated by Django 5.2 on 2025-05-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_perfilusuario_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='titulotercernivel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
