# Generated by Django 5.2 on 2025-05-26 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_documentosusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentosusuario',
            old_name='user',
            new_name='usuario',
        ),
    ]
