# Generated by Django 5.2 on 2025-05-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_rename_user_documentosusuario_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentosusuario',
            name='documento',
        ),
        migrations.AddField(
            model_name='documentosusuario',
            name='comprobantepago',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='documentosusuario',
            name='experiencialaboral',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='documentosusuario',
            name='observacioncomprobantepago',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentosusuario',
            name='observacionexperiencialaboral',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentosusuario',
            name='observacionsolicitudinscripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentosusuario',
            name='observaciontitulo3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentosusuario',
            name='solicitudinscripcion',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='documentosusuario',
            name='titulo3',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AlterField(
            model_name='documentosusuario',
            name='fecha_subida',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
