# Generated by Django 5.2 on 2025-05-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_remove_documentosusuario_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosusuario',
            name='estado_comprobantepago',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='enviado', max_length=20),
        ),
        migrations.AddField(
            model_name='documentosusuario',
            name='estado_experiencialaboral',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='enviado', max_length=20),
        ),
        migrations.AddField(
            model_name='documentosusuario',
            name='estado_solicitudinscripcion',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='enviado', max_length=20),
        ),
        migrations.AddField(
            model_name='documentosusuario',
            name='estado_titulo3',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='enviado', max_length=20),
        ),
    ]
