# Generated by Django 5.2 on 2025-05-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_documentosusuario_estado_comprobantepago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosusuario',
            name='estado_comprobantepago',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosusuario',
            name='estado_experiencialaboral',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosusuario',
            name='estado_solicitudinscripcion',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosusuario',
            name='estado_titulo3',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='Pendiente', max_length=20),
        ),
    ]
