# Generated by Django 5.2 on 2025-06-02 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_alter_documentosusuario_estado_comprobantepago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosUsuarioPEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidadmedica', models.BigIntegerField()),
                ('docidentificacion', models.FileField(blank=True, null=True, upload_to='documentospem/')),
                ('observaciondocidentificacion', models.TextField(blank=True, null=True)),
                ('estado_docidentificacion', models.CharField(choices=[('enviado', 'Enviado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='Pendiente', max_length=20)),
                ('titulosenescyt', models.FileField(blank=True, null=True, upload_to='documentospem/')),
                ('observaciontitulosenescyt', models.TextField(blank=True, null=True)),
                ('estado_titulosenescyt', models.CharField(choices=[('enviado', 'Enviado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='Pendiente', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario')),
            ],
        ),
        migrations.DeleteModel(
            name='DocumentosUsuario',
        ),
    ]
