# Generated by Django 5.2 on 2025-06-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_matriculausuario_matriculadocentemodulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculadocentemodulo',
            name='programa',
            field=models.BigIntegerField(default=9),
            preserve_default=False,
        ),
    ]
