# Generated by Django 5.2 on 2025-06-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_alter_perfilusuario_rol'),
        ('usuarios', '0016_matriculadocentemodulo_programa'),
    ]

    operations = [
    ]
