# Generated by Django 5.2 on 2025-06-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_merge_20250623_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.IntegerField(blank=True, choices=[(1, 'Estudiante'), (2, 'Docente'), (3, 'Coordinador'), (4, 'Editor'), (5, 'Tutor'), (6, 'Técnico'), (7, 'Analista')], null=True),
        ),
    ]
