# Generated by Django 5.2 on 2025-06-23 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_alter_perfilusuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='titulotercernivel',
        ),
        migrations.CreateModel(
            name='PerfilAcademicoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_grado', models.CharField(blank=True, max_length=100, null=True)),
                ('titulo_postgrado_maestria', models.CharField(blank=True, max_length=100, null=True)),
                ('titulo_postgrado_doctorado', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario')),
            ],
        ),
    ]
