# Generated by Django 5.2 on 2025-07-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_remove_perfilusuario_titulotercernivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='ci',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
