# Generated by Django 5.2 on 2025-11-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_alter_perfilusuario_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.IntegerField(blank=True, choices=[(1, 'Estudiante'), (2, 'Docente'), (3, 'Coordinador'), (4, 'Editor'), (5, 'Tutor'), (6, 'Técnico'), (7, 'Analista - DB Posgrado')], null=True),
        ),
    ]
