# Generated by Django 5.2 on 2026-02-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('usuarios', '0021_alter_perfilusuario_rol'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matriculadocentemodulo',
            unique_together={('programa', 'content_type', 'object_id')},
        ),
    ]
