# Generated by Django 5.2 on 2026-03-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_alter_matriculadocentemodulo_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.IntegerField(blank=True, choices=[(1, 'Estudiante'), (2, 'Docente'), (3, 'Coordinador'), (4, 'Editor'), (5, 'Tutor'), (6, 'Técnico'), (7, 'Analista - DB Posgrado'), (8, 'Técnico Contratos')], null=True),
        ),
    ]
