# Generated by Django 5.2 on 2025-04-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('created', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True)),
                ('informacion', models.TextField(blank=True)),
                ('important', models.BooleanField(default=False)),
            ],
        ),
    ]
