# Generated by Django 5.2 on 2025-04-25 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaacademico', '0001_initial'),
        ('programasposgrado', '0005_alter_cohortes_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admision',
            name='important',
        ),
        migrations.RemoveField(
            model_name='admision',
            name='informacion',
        ),
        migrations.AddField(
            model_name='admision',
            name='programadeposgrado',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='programadeposgrado', to='programasposgrado.maestriacohortemodalidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admision',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
