# Generated by Django 5.2 on 2025-04-29 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaacademico', '0002_remove_admision_important_and_more'),
        ('programasposgrado', '0005_alter_cohortes_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisenoCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipodedato', models.IntegerField(choices=[(1, 'Tipo 1'), (2, 'Tipo 2'), (3, 'Tipo 3')])),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('programadeposgrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programadeposgrado_disenocurricular', to='programasposgrado.maestriacohortemodalidad')),
            ],
        ),
    ]
