# Generated by Django 5.2 on 2025-05-07 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaacademico', '0003_disenocurricular'),
        ('programasposgrado', '0005_alter_cohortes_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disenocurricular',
            name='tipodedato',
            field=models.IntegerField(choices=[(1, 'Perfil de egreso'), (2, 'Plan de estudios'), (3, 'Sillabus'), (4, 'Sillabus aprobados')]),
        ),
        migrations.CreateModel(
            name='Titulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipodedato', models.IntegerField(choices=[(1, 'Examen de grado'), (2, 'Trabajo de titulación'), (3, 'Tesis'), (4, 'Trabajo final de titulación')])),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('programadeposgrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programadeposgrado_titulacion', to='programasposgrado.maestriacohortemodalidad')),
            ],
        ),
    ]
