# Generated by Django 5.2 on 2025-05-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaacademico', '0004_alter_disenocurricular_tipodedato_titulacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulacion',
            name='tipodedato',
            field=models.IntegerField(choices=[(1, 'Proyecto de titulación con componente de investigación aplicada y/o desarrollo'), (2, 'Artículos científicos o profesionales de alto nivel'), (3, 'Examen Complexivo teórico – práctico')]),
        ),
    ]
