# Generated by Django 5.2 on 2025-05-15 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaacademico', '0005_alter_titulacion_tipodedato'),
        ('programasposgrado', '0010_programaposgrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admision',
            name='programadeposgrado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programadeposgrado', to='programasposgrado.programaposgrado'),
        ),
        migrations.AlterField(
            model_name='disenocurricular',
            name='programadeposgrado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programadeposgrado_disenocurricular', to='programasposgrado.programaposgrado'),
        ),
        migrations.AlterField(
            model_name='titulacion',
            name='programadeposgrado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programadeposgrado_titulacion', to='programasposgrado.programaposgrado'),
        ),
    ]
