# Generated by Django 5.2 on 2025-07-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaacademico', '0006_alter_admision_programadeposgrado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admision',
            name='tipodedato',
            field=models.IntegerField(choices=[(1, 'Incritos'), (2, 'Matriculados')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admision',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
