# Generated by Django 5.2 on 2025-07-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaacademico', '0007_admision_tipodedato_alter_admision_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admision',
            name='valor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
