# Generated by Django 5.2 on 2025-07-01 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programaacademico', '0008_alter_admision_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admision',
            name='nombre',
        ),
    ]
