# Generated by Django 5.2 on 2025-10-02 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programasposgrado', '0014_maestrias_resolucion_maestrias_titulootorgado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinadorContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=100)),
                ('numero_certificacion_presupuestaria', models.CharField(max_length=100)),
                ('monto_honorarios', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_contrato', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('moneda', models.CharField(default='USD', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('coordinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_coordinador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrato Coordinador',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CoordinadorPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_pago', models.CharField(max_length=20)),
                ('numero_factura', models.CharField(max_length=100)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_cur_pago', models.CharField(max_length=100)),
                ('moneda', models.CharField(default='USD', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_contrato', to='administracionposgrado.coordinadorcontrato')),
                ('coordinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_coordinador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago Coordinador',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CoordinadorPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('coordinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_coordinador', to=settings.AUTH_USER_MODEL)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinadores_programa', to='programasposgrado.programaposgrado')),
            ],
            options={
                'verbose_name': 'Coordinador Programa',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ValorProgramaPosgrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorinscripcion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valormatricula', models.DecimalField(decimal_places=2, max_digits=10)),
                ('primeracolegiatura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('segundacolegiatura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(default='USD', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('programa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valor_programa', to='programasposgrado.programaposgrado')),
            ],
            options={
                'verbose_name': 'Valor Programa de Posgrado',
                'ordering': ['-created'],
            },
        ),
    ]
