# Generated by Django 5.2 on 2025-10-06 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracionposgrado', '0001_initial'),
        ('datosposgrado', '0008_alter_contratocoordinador_options'),
        ('programasposgrado', '0014_maestrias_resolucion_maestrias_titulootorgado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinadorcontrato',
            name='coordinador',
        ),
        migrations.AlterField(
            model_name='coordinadorpagos',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_contrato', to='datosposgrado.contratocoordinador'),
        ),
        migrations.AlterModelOptions(
            name='coordinadorpagos',
            options={'ordering': ['-created'], 'verbose_name': 'Pago Coordinador', 'verbose_name_plural': 'Pagos Coordinadores'},
        ),
        migrations.AlterModelOptions(
            name='coordinadorprograma',
            options={'ordering': ['-fecha_inicio', '-created'], 'verbose_name': 'Coordinador Programa'},
        ),
        migrations.AddField(
            model_name='coordinadorpagos',
            name='programa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_programa', to='programasposgrado.programaposgrado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coordinadorpagos',
            name='coordinador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_coordinador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coordinadorpagos',
            name='mes_pago',
            field=models.DateField(help_text='Usa el primer día del mes pagado (e.g., 2025-10-01).'),
        ),
        migrations.AlterField(
            model_name='coordinadorpagos',
            name='numero_cur_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coordinadorprograma',
            name='coordinador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas_coordinador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coordinadorprograma',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordinadores_programa', to='programasposgrado.programaposgrado'),
        ),
        migrations.AlterField(
            model_name='valorprogramaposgrado',
            name='programa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='valor_programa', to='programasposgrado.programaposgrado'),
        ),
        migrations.AddIndex(
            model_name='coordinadorpagos',
            index=models.Index(fields=['programa', 'mes_pago'], name='administrac_program_43429e_idx'),
        ),
        migrations.AddIndex(
            model_name='coordinadorpagos',
            index=models.Index(fields=['coordinador', 'mes_pago'], name='administrac_coordin_d83dc2_idx'),
        ),
        migrations.AddIndex(
            model_name='coordinadorpagos',
            index=models.Index(fields=['contrato', 'numero_factura'], name='administrac_contrat_d547fc_idx'),
        ),
        migrations.AddIndex(
            model_name='coordinadorprograma',
            index=models.Index(fields=['programa', 'fecha_inicio'], name='administrac_program_35a2b9_idx'),
        ),
        migrations.AddIndex(
            model_name='coordinadorprograma',
            index=models.Index(fields=['programa', 'coordinador'], name='administrac_program_d0ad11_idx'),
        ),
        migrations.AddConstraint(
            model_name='coordinadorpagos',
            constraint=models.UniqueConstraint(fields=('contrato', 'mes_pago', 'numero_factura'), name='uniq_contrato_mes_factura'),
        ),
        migrations.DeleteModel(
            name='CoordinadorContrato',
        ),
    ]
