# Generated by Django 5.2 on 2025-10-06 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracionposgrado', '0002_remove_coordinadorcontrato_coordinador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinadorpagos',
            old_name='numero_cur_pago',
            new_name='numero_oficio_tramite',
        ),
    ]
