# Generated by Django 5.2 on 2025-10-06 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracionposgrado', '0003_rename_numero_cur_pago_coordinadorpagos_numero_oficio_tramite'),
        ('datosposgrado', '0008_alter_contratocoordinador_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoDocenteGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_contratacion', models.DateField(blank=True, null=True)),
                ('pago_realizado', models.BooleanField(default=False)),
                ('numero_factura', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gestion', to='datosposgrado.contratosdocentes')),
            ],
            options={
                'verbose_name': 'Gestión de Contrato Docente',
                'ordering': ['-created'],
            },
        ),
    ]
