# Generated by Django 5.2 on 2025-10-06 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracionposgrado', '0004_contratodocentegestion'),
        ('datosposgrado', '0008_alter_contratocoordinador_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratodocentegestion',
            name='contrato',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gestion', to='datosposgrado.contratosdocentes'),
        ),
    ]
