# Generated by Django 5.2 on 2025-10-14 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracionposgrado', '0005_alter_contratodocentegestion_contrato'),
        ('datosposgrado', '0008_alter_contratocoordinador_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratodocentegestion',
            name='contrato',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gestion', to='datosposgrado.contratosdocentes'),
        ),
        migrations.CreateModel(
            name='ContratoTutorGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_contratacion', models.DateField(blank=True, null=True)),
                ('defendido', models.BooleanField(default=False, help_text='Defendido el trabajo de titulación')),
                ('pago_realizado', models.BooleanField(default=False)),
                ('numero_factura', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gestion', to='datosposgrado.contratotutor')),
            ],
            options={
                'verbose_name': 'Gestión Contrato Tutor',
                'ordering': ['-created'],
            },
        ),
    ]
