# Generated by Django 5.2 on 2025-10-14 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracionposgrado', '0006_alter_contratodocentegestion_contrato_and_more'),
        ('programasposgrado', '0015_modalidaddetitulacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudianteProgramaGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago_inscripcion', models.BooleanField(default=False)),
                ('pago_matricula', models.BooleanField(default=False)),
                ('pago_primera_colegiatura', models.BooleanField(default=False)),
                ('pago_segunda_colegiatura', models.BooleanField(default=False)),
                ('fecha_rubrica_aprobada', models.DateField(blank=True, null=True)),
                ('tutor_resolucion', models.CharField(blank=True, max_length=100, null=True)),
                ('tutor_resolucion_fecha', models.DateField(blank=True, null=True)),
                ('tutor_contratado', models.BooleanField(default=False)),
                ('avance_porcentaje', models.IntegerField(blank=True, choices=[(0, '0 %'), (25, '25 %'), (50, '50 %'), (75, '75 %'), (100, '100 %')], null=True)),
                ('fecha_sustentacion_oral', models.DateField(blank=True, null=True)),
                ('fecha_aprob_complexivo', models.DateField(blank=True, null=True)),
                ('estado_titulo', models.CharField(blank=True, choices=[('SICOA', 'Subido al SICOA'), ('IMPRESION', 'Envío a impresión'), ('REGISTRO', 'Registro Senescyt'), ('LISTO_RETIRO', 'Listo para retiro'), ('ENTREGADO', 'Entregado al estudiante')], max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('modalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programasposgrado.modalidaddetitulacion')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gestiones_estudiantes', to='programasposgrado.programaposgrado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones_estudiante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gestión Estudiante en Programa',
                'ordering': ['-updated', '-created'],
                'unique_together': {('usuario', 'programa')},
            },
        ),
    ]
