# Generated by Django 5.2 on 2025-10-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracionposgrado', '0007_estudianteprogramagestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorprogramaposgrado',
            name='cuota_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='valorprogramaposgrado',
            name='plan_pago',
            field=models.CharField(choices=[('2_COLEGIATURAS', '2 colegiaturas'), ('10_CUOTAS', '10 cuotas')], default='2_COLEGIATURAS', max_length=20),
        ),
        migrations.AddField(
            model_name='valorprogramaposgrado',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='valorprogramaposgrado',
            name='primeracolegiatura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='valorprogramaposgrado',
            name='segundacolegiatura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
