# Generated by Django 5.2 on 2025-10-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracionposgrado', '0008_valorprogramaposgrado_cuota_mensual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valorprogramaposgrado',
            name='plan_pago',
            field=models.CharField(choices=[('10_CUOTAS', '10 cuotas'), ('2_COLEGIATURAS', '2 colegiaturas')], default='10_CUOTAS', max_length=20),
        ),
    ]
