# Generated by Django 5.2 on 2025-10-22 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracionposgrado', '0009_alter_valorprogramaposgrado_plan_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudianteprogramagestion',
            name='cuotas_pagadas',
            field=models.PositiveSmallIntegerField(default=0, help_text='Número de cuotas pagadas cuando el plan del programa es 10 cuotas.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
