# Generated by Django 5.2 on 2025-10-22 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracionposgrado', '0010_estudianteprogramagestion_cuotas_pagadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudianteprogramagestion',
            name='cuotas_pagadas',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Número de cuotas pagadas cuando el plan del programa es 10 cuotas.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
