# Generated by Django 5.2 on 2026-03-02 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracionposgrado', '0011_alter_estudianteprogramagestion_cuotas_pagadas'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('datosposgrado', '0013_remove_contratocoordinador_programa_tipo_and_more'),
        ('programasposgrado', '0015_modalidaddetitulacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='coordinadorpagos',
            name='administrac_program_43429e_idx',
        ),
        migrations.RemoveIndex(
            model_name='coordinadorprograma',
            name='administrac_program_35a2b9_idx',
        ),
        migrations.RemoveIndex(
            model_name='coordinadorprograma',
            name='administrac_program_d0ad11_idx',
        ),
        migrations.AlterUniqueTogether(
            name='estudianteprogramagestion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='coordinadorpagos',
            name='programa',
        ),
        migrations.RemoveField(
            model_name='coordinadorprograma',
            name='programa',
        ),
        migrations.RemoveField(
            model_name='valorprogramaposgrado',
            name='programa',
        ),
        migrations.AddField(
            model_name='coordinadorpagos',
            name='programa_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'programasposgrado'), ('model', 'programaposgrado')), models.Q(('app_label', 'programasposgrado'), ('model', 'programaposgradoem')), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ct_pagos_programa', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='coordinadorpagos',
            name='programa_object_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='coordinadorprograma',
            name='programa_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'programasposgrado'), ('model', 'programaposgrado')), models.Q(('app_label', 'programasposgrado'), ('model', 'programaposgradoem')), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ct_coordinador_programa', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='coordinadorprograma',
            name='programa_object_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='estudianteprogramagestion',
            name='programa_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'programasposgrado'), ('model', 'programaposgrado')), models.Q(('app_label', 'programasposgrado'), ('model', 'programaposgradoem')), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ct_gestion_estudiante_programa', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='estudianteprogramagestion',
            name='programa_object_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='valorprogramaposgrado',
            name='programa_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'programasposgrado'), ('model', 'programaposgrado')), models.Q(('app_label', 'programasposgrado'), ('model', 'programaposgradoem')), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ct_valor_programa', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='valorprogramaposgrado',
            name='programa_object_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='coordinadorpagos',
            index=models.Index(fields=['programa_content_type', 'programa_object_id', 'mes_pago'], name='administrac_program_e92fcf_idx'),
        ),
        migrations.AddIndex(
            model_name='coordinadorprograma',
            index=models.Index(fields=['programa_content_type', 'programa_object_id', 'fecha_inicio'], name='administrac_program_be8f86_idx'),
        ),
        migrations.AddIndex(
            model_name='coordinadorprograma',
            index=models.Index(fields=['programa_content_type', 'programa_object_id', 'coordinador'], name='administrac_program_2d674e_idx'),
        ),
        migrations.AddIndex(
            model_name='estudianteprogramagestion',
            index=models.Index(fields=['programa_content_type', 'programa_object_id'], name='administrac_program_391342_idx'),
        ),
        migrations.AddIndex(
            model_name='estudianteprogramagestion',
            index=models.Index(fields=['usuario', 'updated'], name='administrac_usuario_52429d_idx'),
        ),
        migrations.AddIndex(
            model_name='valorprogramaposgrado',
            index=models.Index(fields=['programa_content_type', 'programa_object_id'], name='administrac_program_222075_idx'),
        ),
        migrations.AddConstraint(
            model_name='estudianteprogramagestion',
            constraint=models.UniqueConstraint(fields=('usuario', 'programa_content_type', 'programa_object_id'), name='uniq_estudiante_programa_gfk'),
        ),
        migrations.AddConstraint(
            model_name='valorprogramaposgrado',
            constraint=models.UniqueConstraint(fields=('programa_content_type', 'programa_object_id'), name='uniq_valor_programa_gfk'),
        ),
        migrations.RemoveField(
            model_name='estudianteprogramagestion',
            name='programa',
        ),
    ]
