# Generated by Django 5.2 on 2026-03-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracionposgrado', '0012_remove_coordinadorpagos_administrac_program_43429e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratodocentegestion',
            name='urlfactura',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contratotutorgestion',
            name='urlfactura',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='coordinadorpagos',
            name='urlfactura',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
