# Generated by Django 5.2 on 2026-03-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracionposgrado', '0013_contratodocentegestion_urlfactura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudianteprogramagestion',
            name='pago_inscripcion',
            field=models.BooleanField(default=True),
        ),
    ]
