# Generated by Django 5.2 on 2026-04-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracionposgrado', '0014_alter_estudianteprogramagestion_pago_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudianteprogramagestion',
            name='tutor_resolucion',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
