# Generated by Django 5.2 on 2026-06-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracionposgrado', '0015_alter_estudianteprogramagestion_tutor_resolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorprogramaposgrado',
            name='inscritos_no_matriculados',
            field=models.PositiveIntegerField(default=0, help_text='Número de inscritos que pagaron inscripción pero no fueron matriculados en el programa.'),
        ),
    ]
