# Generated by Django 5.2 on 2026-06-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracionposgrado', '0016_valorprogramaposgrado_inscritos_no_matriculados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valorprogramaposgrado',
            name='inscritos_no_matriculados',
        ),
        migrations.AddField(
            model_name='valorprogramaposgrado',
            name='total_inscritos',
            field=models.PositiveIntegerField(default=0, help_text='Total de personas inscritas al programa, se hayan matriculado o no.'),
        ),
    ]
