# Generated by Django 5.2 on 2026-06-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracionposgrado', '0017_remove_valorprogramaposgrado_inscritos_no_matriculados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudianteprogramagestion',
            name='beca_documento_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='estudianteprogramagestion',
            name='beca_porcentaje',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sin beca'), (25, '25%'), (50, '50%'), (75, '75%'), (100, '100%')], default=0),
        ),
    ]
