# Generated by Django 5.2 on 2026-06-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracionposgrado', '0018_estudianteprogramagestion_beca_documento_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudianteprogramagestion',
            name='reingreso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudianteprogramagestion',
            name='reingreso_documento_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='estudianteprogramagestion',
            name='reingreso_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudianteprogramagestion',
            name='retirado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudianteprogramagestion',
            name='retiro_documento_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='estudianteprogramagestion',
            name='retiro_fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
