# Generated by Django 5.2 on 2026-01-22 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaConocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Área de conocimiento',
                'verbose_name_plural': 'Áreas de conocimiento',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CampoConocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Campo de conocimiento',
                'verbose_name_plural': 'Campos de conocimiento',
                'ordering': ['subarea__area__codigo', 'subarea__codigo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='SubareaConocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=200)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subareas', to='perfeccionamientodocente.areaconocimiento')),
            ],
            options={
                'verbose_name': 'Subárea de conocimiento',
                'verbose_name_plural': 'Subáreas de conocimiento',
                'ordering': ['area__codigo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='CursoCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('dirigido_a', models.CharField(blank=True, max_length=255, null=True)),
                ('carrera', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('horario', models.CharField(blank=True, max_length=200, null=True)),
                ('horas_totales', models.PositiveIntegerField(default=40)),
                ('num_docentes_dirigido', models.PositiveIntegerField(blank=True, null=True)),
                ('facilitador_nombres', models.CharField(blank=True, max_length=255, null=True)),
                ('facilitador_cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('interno_externo', models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], default='interno', max_length=10)),
                ('financiamiento', models.CharField(choices=[('presupuesto', 'Presupuesto'), ('autogestion', 'Autogestión')], default='presupuesto', max_length=20)),
                ('presupuesto_monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('modalidad', models.CharField(choices=[('virtual', 'Virtual'), ('presencial', 'Presencial'), ('hibrida', 'Híbrida')], default='virtual', max_length=10)),
                ('lugar', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='perfeccionamientodocente.areaconocimiento')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='perfeccionamientodocente.campoconocimiento')),
                ('facilitador', models.ForeignKey(blank=True, limit_choices_to={'perfilusuario__rol': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_facilitados', to=settings.AUTH_USER_MODEL)),
                ('subarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='perfeccionamientodocente.subareaconocimiento')),
            ],
            options={
                'verbose_name': 'Curso de capacitación',
                'verbose_name_plural': 'Cursos de capacitación',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='campoconocimiento',
            name='subarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campos', to='perfeccionamientodocente.subareaconocimiento'),
        ),
        migrations.CreateModel(
            name='CursoParticipacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('rol', models.CharField(choices=[('participante', 'Participante'), ('facilitador', 'Facilitador'), ('ambos', 'Ambos')], default='participante', max_length=20)),
                ('estado', models.CharField(choices=[('inscrito', 'Inscrito'), ('enviado', 'Enviado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('finalizado', 'Finalizado')], default='inscrito', max_length=20)),
                ('certificado', models.FileField(blank=True, null=True, upload_to='certificados_perfeccionamiento/')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='perfeccionamientodocente.cursocapacitacion')),
                ('docente', models.ForeignKey(limit_choices_to={'perfilusuario__rol': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participación en curso',
                'verbose_name_plural': 'Participaciones en cursos',
                'ordering': ['-fecha_registro'],
                'constraints': [models.UniqueConstraint(fields=('curso', 'docente', 'content_type', 'object_id'), name='uq_participacion_curso_docente_programa')],
            },
        ),
        migrations.AddConstraint(
            model_name='subareaconocimiento',
            constraint=models.UniqueConstraint(fields=('area', 'codigo'), name='uq_subarea_area_codigo'),
        ),
        migrations.AddConstraint(
            model_name='campoconocimiento',
            constraint=models.UniqueConstraint(fields=('subarea', 'codigo'), name='uq_campo_subarea_codigo'),
        ),
    ]
