# Generated by Django 5.2 on 2026-01-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfeccionamientodocente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoparticipacion',
            name='estado_resultado',
            field=models.CharField(blank=True, choices=[('aprobado', 'Aprobado'), ('reprobado', 'Reprobado')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cursoparticipacion',
            name='nota_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cursoparticipacion',
            name='porcentaje_asistencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cursocapacitacion',
            name='dirigido_a',
            field=models.CharField(blank=True, default='Posgrado', max_length=255, null=True),
        ),
    ]
