# Generated by Django 5.2 on 2026-01-28 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('perfeccionamientodocente', '0002_cursoparticipacion_estado_resultado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoparticipacion',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='cursoparticipacion',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
