# Generated by Django 5.2 on 2025-06-23 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seleccionperfiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ternamodulopm',
            options={'verbose_name': 'Terna de Módulo Maestría', 'verbose_name_plural': 'Ternas de Módulo Maestría'},
        ),
        migrations.RemoveField(
            model_name='ternamodulopm',
            name='docente1_idoneo',
        ),
        migrations.RemoveField(
            model_name='ternamodulopm',
            name='docente2',
        ),
        migrations.RemoveField(
            model_name='ternamodulopm',
            name='docente3',
        ),
        migrations.AlterField(
            model_name='ternamodulopm',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='ternamodulopm',
            name='docente1_idoneo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ternas_idoneo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ternamodulopm',
            name='docente2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ternas_docente2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ternamodulopm',
            name='docente3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ternas_docente3', to=settings.AUTH_USER_MODEL),
        ),
    ]
