# Generated by Django 5.2 on 2025-06-23 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seleccionperfiles', '0002_alter_ternamodulopm_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ternamodulopm',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ternas_responsable', to=settings.AUTH_USER_MODEL),
        ),
    ]
