# Generated by Django 5.2 on 2025-07-16 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programasposgrado', '0013_especialidadesmedicas_programaposgradoem_modulosem'),
        ('seleccionperfiles', '0003_ternamodulopm_responsable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TernaModuloCoordinadorPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('coordinador2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ternas_coordinador2', to=settings.AUTH_USER_MODEL)),
                ('coordinador3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ternas_coordinador3', to=settings.AUTH_USER_MODEL)),
                ('coordinador_idoneo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ternas_coordinador_idoneo', to=settings.AUTH_USER_MODEL)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terna_modulocoordinadorpm', to='programasposgrado.modulos')),
                ('programa_posgrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terna_modulocoordinadorpm', to='programasposgrado.programaposgrado')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ternas_coordinador_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Terna de Coordinador de Módulo Maestría',
                'verbose_name_plural': 'Ternas de Coordinador de Módulo Maestría',
            },
        ),
        migrations.CreateModel(
            name='CoordinadorContratadoPM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinador_contratadopm', to=settings.AUTH_USER_MODEL)),
                ('terna_modulo_coordinador_maestria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinador_contratadopm', to='seleccionperfiles.ternamodulocoordinadorpm')),
            ],
            options={
                'verbose_name': 'Coordinador Contratado',
                'verbose_name_plural': 'Coordinadores Contratados',
            },
        ),
    ]
