# Generated by Django 5.2 on 2025-05-12 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuerpoacademico', '0001_initial'),
        ('programasposgrado', '0005_alter_cohortes_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composicionca',
            name='programadeposgrado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programadeposgrado_composicionca', to='programasposgrado.maestriacohortemodalidad'),
        ),
        migrations.CreateModel(
            name='GestionAcademicaCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('tipodedato', models.IntegerField(choices=[(1, 'Composición 1'), (2, 'Composición 2'), (3, 'Composición 3')])),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('programadeposgrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programadeposgrado_gestionacademicaca', to='programasposgrado.maestriacohortemodalidad')),
            ],
        ),
    ]
