# Generated by Django 5.2 on 2025-05-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuerpoacademico', '0002_alter_composicionca_programadeposgrado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestionacademicaca',
            name='tipodedato',
            field=models.IntegerField(choices=[(1, 'Gestion Academica 1'), (2, 'Gestion Academica 2'), (3, 'Gestion Academica 3')]),
        ),
    ]
