# Generated by Django 5.2 on 2025-05-15 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuerpoacademico', '0003_alter_gestionacademicaca_tipodedato'),
        ('programasposgrado', '0010_programaposgrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composicionca',
            name='programadeposgrado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programadeposgrado_composicionca', to='programasposgrado.programaposgrado'),
        ),
        migrations.AlterField(
            model_name='gestionacademicaca',
            name='programadeposgrado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programadeposgrado_gestionacademicaca', to='programasposgrado.programaposgrado'),
        ),
    ]
