# Generated by Django 5.2 on 2025-05-15 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programasposgrado', '0008_modulos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactivosMultipleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('contribucion', models.IntegerField(choices=[(1, 'Alto'), (2, 'Medio'), (3, 'Bajo')])),
                ('opciona', models.TextField()),
                ('opcionb', models.TextField()),
                ('opcionc', models.TextField()),
                ('opciond', models.TextField()),
                ('correcta', models.CharField(choices=[('A', 'Opción A'), ('B', 'Opción B'), ('C', 'Opción C'), ('D', 'Opción D')], max_length=1)),
                ('justificacion', models.TextField()),
                ('bibliografia', models.TextField()),
                ('palabras_clave', models.TextField()),
                ('tiempo_estimado', models.IntegerField()),
                ('estado', models.IntegerField(choices=[(1, 'Enviado'), (2, 'Validado'), (3, 'No validado')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.IntegerField(blank=True, null=True)),
                ('usuario', models.IntegerField(blank=True, null=True)),
                ('programadeposgrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programa_reactivos', to='programasposgrado.maestriacohortemodalidad')),
            ],
            options={
                'verbose_name': 'Reactivo',
                'ordering': ['-created'],
            },
        ),
    ]
