# Generated by Django 5.2 on 2025-05-15 13:25

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rae', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactivosmultiplechoice',
            name='enunciado',
            field=tinymce.models.HTMLField(),
        ),
    ]
