# Generated by Django 5.2 on 2025-05-15 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programasposgrado', '0010_programaposgrado'),
        ('rae', '0002_alter_reactivosmultiplechoice_enunciado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactivosmultiplechoice',
            name='programadeposgrado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programa_reactivos', to='programasposgrado.programaposgrado'),
        ),
    ]
