# Generated by Django 5.2 on 2025-06-11 17:42

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rae', '0003_alter_reactivosmultiplechoice_programadeposgrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactivosmultiplechoice',
            name='enunciado',
            field=tinymce.models.HTMLField(unique=True),
        ),
    ]
