# Generated by Django 5.2 on 2025-06-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rae', '0004_alter_reactivosmultiplechoice_enunciado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactivosmultiplechoice',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Enviado'), (2, 'Validado'), (3, 'Rechazado')], default=1),
        ),
    ]
