# Generated by Django 5.2 on 2025-07-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rae', '0005_alter_reactivosmultiplechoice_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactivosmultiplechoice',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
