# Generated by Django 5.2 on 2025-07-07 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programasposgrado', '0013_especialidadesmedicas_programaposgradoem_modulosem'),
        ('rae', '0006_reactivosmultiplechoice_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactivosModuloRAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.IntegerField()),
                ('numero_reactivos_modulo', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('programadeposgrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programa_reactivosmodulorae', to='programasposgrado.programaposgrado')),
            ],
            options={
                'verbose_name': 'ReactivosModuloRAE',
                'verbose_name_plural': 'ReactivosModuloRAE',
            },
        ),
    ]
