# Generated by Django 5.2 on 2025-07-08 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programasposgrado', '0013_especialidadesmedicas_programaposgradoem_modulosem'),
        ('rae', '0007_reactivosmodulorae'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('simulacro', 'Simulacro'), ('final', 'Final')], max_length=10)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('activa', models.BooleanField(default=False)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programasposgrado.programaposgrado')),
            ],
            options={
                'unique_together': {('programa', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='EvaluacionEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('respondido', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rae.evaluacionprograma')),
            ],
        ),
        migrations.CreateModel(
            name='ReactivoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_estudiante', models.CharField(blank=True, max_length=1, null=True)),
                ('correcta', models.BooleanField(default=False)),
                ('evaluacion_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rae.evaluacionestudiante')),
                ('reactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rae.reactivosmultiplechoice')),
            ],
        ),
    ]
