# Generated by Django 5.2 on 2025-07-09 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programasposgrado', '0013_especialidadesmedicas_programaposgradoem_modulosem'),
        ('rae', '0008_evaluacionprograma_evaluacionestudiante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactivosmultiplechoice',
            name='modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programasposgrado.modulos'),
        ),
    ]
