# Generated by Django 5.2 on 2025-07-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rae', '0009_alter_reactivosmultiplechoice_modulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactivosmultiplechoice',
            name='modulo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
