# Generated by Django 5.2 on 2025-07-09 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programasposgrado', '0013_especialidadesmedicas_programaposgradoem_modulosem'),
        ('rae', '0011_alter_reactivosmultiplechoice_modulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactivosmodulorae',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programasposgrado.modulos'),
        ),
    ]
