# Generated by Django 5.2 on 2025-07-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rae', '0012_alter_reactivosmodulorae_modulo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evaluacionprograma',
            unique_together=set(),
        ),
    ]
