# Generated by Django 5.2 on 2025-07-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rae', '0013_alter_evaluacionprograma_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionprograma',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
