# Generated by Django 5.2 on 2025-08-07 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rae', '0014_evaluacionprograma_duracion_minutos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactivoPorEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rae.evaluacionprograma')),
                ('reactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rae.reactivosmultiplechoice')),
            ],
            options={
                'unique_together': {('evaluacion', 'reactivo')},
            },
        ),
    ]
