# Generated by Django 5.2 on 2025-08-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rae', '0015_reactivoporevaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionprograma',
            name='valorpregunta',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='evaluacionprograma',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=90),
        ),
    ]
