# Generated by Django 5.2 on 2025-08-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rae', '0016_evaluacionprograma_valorpregunta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionprograma',
            name='valorpregunta',
            field=models.DecimalField(decimal_places=3, default=2.0, max_digits=5),
        ),
    ]
