# Generated by Django 5.2 on 2025-10-27 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programasposgrado', '0015_modalidaddetitulacion'),
        ('rae', '0017_alter_evaluacionprograma_valorpregunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponenteRAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('preguntas_sugeridas', models.PositiveIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes_rae', to='programasposgrado.programaposgrado')),
            ],
            options={
                'verbose_name': 'Componente RAE',
                'verbose_name_plural': 'Componentes RAE',
                'ordering': ['programa', 'orden', 'id'],
                'unique_together': {('programa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='SubcomponenteRAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('preguntas_sugeridas', models.PositiveIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcomponentes', to='rae.componenterae')),
            ],
            options={
                'verbose_name': 'Subcomponente RAE',
                'verbose_name_plural': 'Subcomponentes RAE',
                'ordering': ['componente', 'orden', 'id'],
                'unique_together': {('componente', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='SubcomponenteModuloRAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_rae', to='programasposgrado.modulos')),
                ('subcomponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos_asignados', to='rae.subcomponenterae')),
            ],
            options={
                'verbose_name': 'Asignación de módulo a subcomponente',
                'verbose_name_plural': 'Asignaciones de módulos a subcomponentes',
                'unique_together': {('subcomponente', 'modulo')},
            },
        ),
    ]
