# Generated by Django 5.2 on 2025-10-27 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rae', '0018_componenterae_subcomponenterae_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componenterae',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='componenterae',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='subcomponenterae',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='subcomponenterae',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='subcomponenterae',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='subcomponenterae',
            name='preguntas_sugeridas',
        ),
    ]
