# Generated by Django 5.2 on 2026-01-21 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programasposgrado', '0015_modalidaddetitulacion'),
        ('rae', '0019_remove_componenterae_activo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactivoCompartidoPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactivos_compartidos', to='programasposgrado.programaposgrado')),
                ('reactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartido_en_programas', to='rae.reactivosmultiplechoice')),
            ],
            options={
                'verbose_name': 'Reactivo compartido a programa',
                'verbose_name_plural': 'Reactivos compartidos a programas',
                'unique_together': {('programa', 'reactivo')},
            },
        ),
    ]
