# Generated by Django 5.2 on 2026-04-29 14:36

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rae', '0020_reactivocompartidoprograma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactivosmultiplechoice',
            name='justificacion',
            field=tinymce.models.HTMLField(),
        ),
    ]
